"""A model to test with, made on the spot: ``tiny_model(path)``.

A llama-architecture GGUF with random weights that llama.cpp really loads
and runs — generated by Athanor's own writer in a fraction of a second, so
a host can test its integration (a recording, a load, a template) without
downloading anything. Its words are nonsense; its logits are real.

Nothing ships with a model: this writes one, locally, when asked.

The vocabulary is either a small byte-level one made here (the default:
three special tokens, the 256 bytes, and a few common words), or copied
from any GGUF you name (``vocab_from=``), tokenizer keys and all.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .gguf import Array, GGMLType, GGUFWriter, ValueType
from .gguf import read as read_gguf

WORDS = ("the", "of", "and", "to", "in", "is", "that", "it", "was", "for", "on",
         "radio", "signal", "model", "token", "water", "fall")

CHATML = ("{% for m in messages %}<|im_start|>{{ m['role'] }}\n{{ m['content'] }}"
          "<|im_end|>\n{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n"
          "{% endif %}")


def _byte_vocab() -> tuple[list, list, list]:
    """(tokens, scores, types): SentencePiece-style, with byte fallback."""
    tokens = ["<unk>", "<s>", "</s>", "<|im_start|>", "<|im_end|>"]
    types = [2, 3, 3, 3, 3]                       # unknown, control ×4
    tokens += [f"<0x{b:02X}>" for b in range(256)]
    types += [6] * 256                            # byte
    tokens += ["▁"] + [f"▁{w}" for w in WORDS] + list(WORDS)
    types += [1] * (1 + 2 * len(WORDS))           # normal
    scores = [0.0] * 261 + [-float(i) for i in range(len(tokens) - 261)]
    return tokens, scores, types


def tiny_model(path, *, vocab_from=None, seed: int = 1, n_embd: int = 64,
               n_layers: int = 2, n_ctx: int = 512, template: str | None = None,
               n_experts: int = 0, n_experts_used: int = 2) -> Path:
    """Write a small runnable model to ``path`` (which must not exist) and
    return it. ``vocab_from``: a GGUF whose tokenizer to copy.

    ``n_experts`` > 0 makes it a mixture of experts (Mixtral's layout: a
    router per layer choosing ``n_experts_used`` of ``n_experts`` feed-forward
    blocks for every token) — for testing the Tap's expert map."""
    E, H, HKV, FF = int(n_embd), 4, 2, 2 * int(n_embd)
    if E % H:
        raise ValueError("n_embd must be a multiple of 4")
    NX, NU = int(n_experts), int(n_experts_used)
    if NX and not 0 < NU <= NX:
        raise ValueError("n_experts_used must be between 1 and n_experts")
    rng = np.random.default_rng(seed)
    w = GGUFWriter()
    w.add("general.architecture", "llama")
    w.add("general.name", "Athanor tiny test model")
    w.add("general.file_type", 0, ValueType.UINT32)
    for key, value in (("context_length", n_ctx), ("embedding_length", E),
                       ("block_count", n_layers), ("feed_forward_length", FF),
                       ("attention.head_count", H), ("attention.head_count_kv", HKV),
                       ("rope.dimension_count", E // H)):
        w.add(f"llama.{key}", value, ValueType.UINT32)
    w.add("llama.attention.layer_norm_rms_epsilon", 1e-5, ValueType.FLOAT32)
    if NX:
        w.add("llama.expert_count", NX, ValueType.UINT32)
        w.add("llama.expert_used_count", NU, ValueType.UINT32)
    if vocab_from is not None:
        src = read_gguf(vocab_from)
        n_vocab = len(src.get("tokenizer.ggml.tokens"))
        for kv in src.kvs:
            if kv.key.startswith("tokenizer.") and kv.key != "tokenizer.chat_template":
                if isinstance(kv.value, Array):
                    w.add(kv.key, kv.value.items, ValueType.ARRAY, kv.value.elem_type)
                else:
                    w.add(kv.key, kv.value, kv.type)
    else:
        tokens, scores, types = _byte_vocab()
        n_vocab = len(tokens)
        w.add("tokenizer.ggml.model", "llama")
        w.add("tokenizer.ggml.pre", "default")
        w.add("tokenizer.ggml.tokens", tokens, ValueType.ARRAY, ValueType.STRING)
        w.add("tokenizer.ggml.scores", np.array(scores, np.float32), ValueType.ARRAY,
              ValueType.FLOAT32)
        w.add("tokenizer.ggml.token_type", types, ValueType.ARRAY, ValueType.INT32)
        w.add("tokenizer.ggml.bos_token_id", 1, ValueType.UINT32)
        w.add("tokenizer.ggml.eos_token_id", 4, ValueType.UINT32)   # <|im_end|>
        w.add("tokenizer.ggml.unknown_token_id", 0, ValueType.UINT32)
        w.add("tokenizer.ggml.add_bos_token", True, ValueType.BOOL)
        # no space slipped in after a special token: what the template
        # writes is what the model reads
        w.add("tokenizer.ggml.add_space_prefix", False, ValueType.BOOL)
    w.add("tokenizer.chat_template", template or CHATML)

    def rand(name, shape, scale):
        w.add_tensor(name, shape, GGMLType.F32,
                     (rng.standard_normal(tuple(reversed(shape))) * scale).astype(np.float32))

    ones = np.ones(E, np.float32)
    rand("token_embd.weight", (E, n_vocab), 1.0)
    w.add_tensor("output_norm.weight", (E,), GGMLType.F32, ones)
    for i in range(n_layers):
        w.add_tensor(f"blk.{i}.attn_norm.weight", (E,), GGMLType.F32, ones)
        w.add_tensor(f"blk.{i}.ffn_norm.weight", (E,), GGMLType.F32, ones)
        rand(f"blk.{i}.attn_q.weight", (E, E), 0.2)
        rand(f"blk.{i}.attn_k.weight", (E, E * HKV // H), 0.2)
        rand(f"blk.{i}.attn_v.weight", (E, E * HKV // H), 0.2)
        rand(f"blk.{i}.attn_output.weight", (E, E), 0.2)
        if NX:
            rand(f"blk.{i}.ffn_gate_inp.weight", (E, NX), 0.5)     # the router
            rand(f"blk.{i}.ffn_gate_exps.weight", (E, FF, NX), 0.2)
            rand(f"blk.{i}.ffn_up_exps.weight", (E, FF, NX), 0.2)
            rand(f"blk.{i}.ffn_down_exps.weight", (FF, E, NX), 0.2)
        else:
            rand(f"blk.{i}.ffn_gate.weight", (E, FF), 0.2)
            rand(f"blk.{i}.ffn_up.weight", (E, FF), 0.2)
            rand(f"blk.{i}.ffn_down.weight", (FF, E), 0.2)
    return w.write_file(Path(path))
